### ISSUE TITLE
Kretnje igrača

### ISSUE THREAD

**Issue by MatAci** [LeonIvovic/PI-Projekt#11]
Dodavanje osnovnih kretnji igrača. Kretnje igrača su lijevo, desno i skok. Lijeva kretnja definirana je pritiskom lijeve strelice ili slova a na tipkovnici. Desna kretnja definirana je pritiskom desne strelice ili slova d na tipkovnici. Skok je definiran pritiskom na tipku space.

1.Dodavanje logike iza čitanja ulaznih podataka tipkovnice te pomicanja igrača u zadanom smjeru.
2.Testiranje kretnji lijevo i desno.
3.Dodavanje opcije za skok na način da se odredi koliko visoko igrač može skočiti u ovisnosti o tome koliko dugo zadrži tipku space.
4.Dodavanje brzine kretnje te korekcija da ne postoji mogućnost dvostrukog skoka.
5.Testiranje kretnji tijekom skoka i namještavanje varijabli kako bi kretnja bila ugodna.

**Comment by LeonIvovic** [comment]
Završen u #3 i #19
