### ISSUE TITLE
Dodavanje neprijatelja

### ISSUE THREAD

**Issue by LeonIvovic** [LeonIvovic/PI-Projekt#17]
Dodavanje osnovnog neprijatelja koji oduzima život igraču kada ga dotakne (privremeno rješenje koje kasnije može biti povezano sa GameManagerom #13 ).
Neprijatelj može biti statički ili pokretan.

**Comment by MatAci** [comment]
Kada se zavrsi #34 zadatak dodavanje neprijatelja u treći level
