### ISSUE TITLE
Glavni izbornik

### ISSUE THREAD

**Issue by LeonIvovic** [LeonIvovic/PI-Projekt#22]
Dodavanje menua/izbornika.

1. Početni pri pokretanju igre (Play, exit, highscore...)
2. Pritisak *esc* ili neke druge tipke za vrijeme igre otvara opcije za resetirat level i izaći iz igre, te pauzira igru (ako odlučimo mjeriti vrijeme)

**Comment by BeaverBeliever420** [comment]
![image](https://user-images.githubusercontent.com/127941265/229295129-0db8b5e3-f9fa-4f4b-8aba-c2c9a000fb86.png)
potencijalni icon&menu sprite
