### ISSUE TITLE
Podešavanje GameManager-a između svih levela

### ISSUE THREAD

**Issue by MatAci** [LeonIvovic/PI-Projekt#37]
Kada su kreirani svi leveli potrebno je podesiti automatsko zvanje novog levela kada se prethodni završi. To se radi koristeći GameManager.

**Comment by LeonIvovic** [comment]
Nove levele potrebno je dodati u BuildSettings po ispravnom rasporedu, GameManager bi onda sam trebao uvijek ucitati sljedeci level.

**Comment by MatAci** [comment]
Promjena scene vrši se automatski te je samo pri kreiranju pojedine scene bitno staviti je u build settings
