### ISSUE TITLE
Dodavanje dizajnerskog paket

### ISSUE THREAD

**Issue by MatAci** [LeonIvovic/PI-Projekt#7]
1.Pronalazak paketa sa slikama na Unity Asset Store-u ili internetu.
2.Učitavanje konkretnih sprite-ova u scene.
3.Spajanje sprite-ova sa konkretnim 2D objektima.
4.Dodavanje sprite-ova na smislena mjesta u datotekama.

Ukoliko se kombinira već gotov paket sa našim kreiranim slikama pripaziti da je otprilike isti stil te da se slika slaže u komplet grafičkog dizajna igrice

**Comment by BeaverBeliever420** [comment]
![image](https://user-images.githubusercontent.com/127941265/229294835-389cbea6-60d3-4487-8ed0-fb716c397fd7.png)
napravljen sprite za glavnog lika

**Comment by BeaverBeliever420** [comment]
Pokušao sam razne materijale koristiti za mijenjanje grounda ali svi izgledaju dosta loše pa više smisla ima sastavljati drugačiji sprite no za to trebam konkretne veličine grounda (da ne bi zafrkavalo sa skriptama te da nebi bio užasan scaling)

**Comment by LeonIvovic** [comment]
Bit ce tesko za specificnu velicinu grounda jer ih moze bit puno, a ako stavimo uvijek istu se ogranicavamo na level designu. Unity ima dosta dobre opcije za spritove gdje se napravi za samo jedan segment npr. 16x16 ili bilo koja druga dimenzija i onda se moze postavit odvojeno skaliranje ili ponavljanje istog segmenta, to bi trebalo raditi sa skaliranjem. Ako imas primjer neki mogu ha probat postavit pa vidimo kako izgleda.
